import '../styles/globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
}
const RootLayout = ({ children }) => {
  return (
    <html lang="ja">
      <head>
        {/* 他のメタタグやリンクタグ */}
      </head>
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;